#!/usr/bin/env bash
# a script that install and configure HAproxy on web-02
# distribute requests using a roundwobin algorithm
# HAproxy manages init the script

sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update

# Install HAProxy
sudo apt-get -y install haproxy
sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 201406-web-01 54.146.15.57 check\n\tserver 201406-web-02 100.26.136.37 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
